name: qr_checkin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  go_router: ^13.2.4
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.6.0
  mobile_scanner: ^4.0.1
  qr_flutter: ^4.1.0
  quill_delta: ^3.0.0-nullsafety.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  device_info_plus: ^9.1.2
  quill_html_editor: ^2.2.8
  decimal: ^2.3.3
  flutter_localizations:
    sdk: flutter
  intl: any
  image_picker: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_html: 3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/